// Generated by CoffeeScript 1.3.3
(function() {
  var parse;

  parse = require('url').parse;

  module.exports = function(packages) {
    return function(req, res, next) {
      var path, pkg;
      if (!(req.method === 'GET' || req.method === 'HEAD')) {
        return next();
      }
      path = parse(req.url).pathname;
      if (!(pkg = packages[path])) {
        return next();
      }
      return pkg.compile(function(err, source) {
        if (err) {
          return next(err);
        }
        res.contentType('js');
        return res.send(source);
      });
    };
  };

}).call(this);
